#!/usr/bin/env bash


PKGS=(

    # SYSTEM --------------------------------------------------------------

    	'linux-lts'             # Long term support kernel
    	'linux'			# Regular kernel
    	'linux-headers'		# Header for regular kernel
    	'linux-lts-headers'	# Headers for LTS kernel
    	'linux-firmware'	# Kernel firmware
    	'base-devel'		# Additional devel tools
    	'reflector'		# Pacman mirrorlist 
    	'efibootmgr'
    	'grub'			# Bootloader
    	'os-prober'
    	'grub-btrfs'
    	'btrfs-progs'
    	'dosftools'
    	'mtools'
    	'ntfs-3g'
    	'intel-ucode'		# Intel processor microcode

    # Network --------------------------------------------------------------
     	'networkmanager'
     	'network-manager-applet'
     	'dialog'
     	'reflector'
     	'openssh'
     	'wireless-tools'
     
    # Graphic --------------------------------------------------------------
     	'nvidia'
     	'nvidia-lts'
     	'nvidia-settings'
     
    # Interface --------------------------------------------------------------
      	'i3-gaps'
      	'lightdm-gtk-greeter'
      	'xdg-utils'
      	'xdg-user-dirs'
      	'xorg-server'
      	'xorg-apps'
      	'rofi'
      
    # Audio --------------------------------------------------------------
    	'alsa-utils'
     	'pipewire'
     	'pipewire-alsa'
     	'pipewire-pulse'
     	'pipewire-jack'
	'pamixer'		# Audio mixer
     	'bluez'
     	'bluez-utils'
   
   
    # TERMINAL UTILITIES --------------------------------------------------
	'alacritty'            	# Terminal emulator
        'vim'                   # Terminal Editor
        'zsh'                   # Interactive shell
        'man-db'			
        'man'			# man-pages
        'exa'			# ls substitute
        'bat'			# bat substitute 
	'bpytop'		# Resource monitor

    # GENERAL UTILITIES ---------------------------------------------------
	'thunar'		#Filesystem browser


    # MEDIA ---------------------------------------------------------------
    	'mpv'                   # Video player
    	'feh'                   # Image viewer
    	'python-pywal'          # Wallpaper utility
    	'cups'			# Printin service
	'nitrogen'		# GTK wallpaper chooser
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm --needed
done

services=(
        NetworkManager.service
        lightdm.service
        fstrim.timer
        cups.service
        bluetooth
        reflector.timer 
        snapper-timeline.timer 
        snapper-cleanup.timer 
        grub-btrfs.path 
        
)
for service in "${services[@]}"; do
    systemctl enable "$service" 
done

echo
echo "Done!"
echo
